#!/bin/bash

if [ -e /var/run/reboot-required ]
	then
		python /home/.emails/emailBuilder.py -r
		python /home/.emails/emailSender.py /home/.emails/download_email.txt "Your computer needs to reboot"
fi
